### ISSUE TITLE
guacamole-auth-jwt - java.lang.NoClassDefFoundError: io/jsonwebtoken/JwtException

### ISSUE THREAD

**Issue by cicerofs** [aiden0z/guacamole-auth-jwt#4]
When I use your extension the following error occurred:

00:51:24.841 [http-nio-8080-exec-7] ERROR o.a.g.rest.RESTExceptionWrapper - Unexpected internal error: io/jsonwebtoken/JwtException
00:51:24.873 [http-nio-8080-exec-7] DEBUG o.a.g.rest.RESTExceptionWrapper - Unexpected error in REST endpoint.
java.lang.NoClassDefFoundError: io/jsonwebtoken/JwtException
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[na:1.8.0_141]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[na:1.8.0_141]
	at java.lang.Class.getDeclaredConstructors(Class.java:2020) ~[na:1.8.0_141]
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:243) ~[guice-3.0.jar:na]
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:96) ~[guice-3.0.jar:na]
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:629) ~[guice-3.0.jar:na]
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:845) ~[guice-3.0.jar:na]
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772) ~[guice-3.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256) ~[guice-3.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205) ~[guice-3.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853) ~[guice-3.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:967) ~[guice-3.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1000) ~[guice-3.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:961) ~[guice-3.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013) ~[guice-3.0.jar:na]
	at com.aiden0z.guacamole.net.jwt.JwtAuthenticationProvider.getAuthorizedConfigurations(JwtAuthenticationProvider.java:50) ~[na:na]
	at org.apache.guacamole.net.auth.simple.SimpleAuthenticationProvider.getFilteredAuthorizedConfigurations(SimpleAuthenticationProvider.java:158) ~[guacamole-ext-0.9.13-incubating.jar:na]
	at org.apache.guacamole.net.auth.simple.SimpleAuthenticationProvider.authenticateUser(SimpleAuthenticationProvider.java:217) ~[guacamole-ext-0.9.13-incubating.jar:na]
	at org.apache.guacamole.extension.AuthenticationProviderFacade.authenticateUser(AuthenticationProviderFacade.java:162) ~[classes/:na]
	at org.apache.guacamole.rest.auth.AuthenticationService.authenticateUser(AuthenticationService.java:152) ~[classes/:na]
	at org.apache.guacamole.rest.auth.AuthenticationService.getAuthenticatedUser(AuthenticationService.java:239) ~[classes/:na]
	at org.apache.guacamole.rest.auth.AuthenticationService.authenticate(AuthenticationService.java:383) ~[classes/:na]
	at org.apache.guacamole.rest.auth.TokenRESTService.createToken(TokenRESTService.java:181) ~[classes/:na]
	at org.apache.guacamole.rest.RESTExceptionWrapper.invoke(RESTExceptionWrapper.java:153) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_141]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_141]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.17.1.jar:1.17.1]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185) [jersey-server-1.17.1.jar:1.17.1]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) [jersey-server-1.17.1.jar:1.17.1]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) [jersey-server-1.17.1.jar:1.17.1]
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [jersey-server-1.17.1.jar:1.17.1]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.17.1.jar:1.17.1]
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [jersey-server-1.17.1.jar:1.17.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511) [jersey-server-1.17.1.jar:1.17.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442) [jersey-server-1.17.1.jar:1.17.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391) [jersey-server-1.17.1.jar:1.17.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381) [jersey-server-1.17.1.jar:1.17.1]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416) [jersey-servlet-1.17.1.jar:1.17.1]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538) [jersey-servlet-1.17.1.jar:1.17.1]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716) [jersey-servlet-1.17.1.jar:1.17.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [guice-servlet-3.0.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.26]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.26]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.26]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.26]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:8.0.26]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.26]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.26]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) [catalina.jar:8.0.26]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.26]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [catalina.jar:8.0.26]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-coyote.jar:8.0.26]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673) [tomcat-coyote.jar:8.0.26]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526) [tomcat-coyote.jar:8.0.26]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482) [tomcat-coyote.jar:8.0.26]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_141]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.26]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
Caused by: java.lang.ClassNotFoundException: io.jsonwebtoken.JwtException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_141]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_141]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_141]
	... 67 common frames omitted
31-Oct-2017 00:51:24.883 SEVERE [http-nio-8080-exec-7] com.sun.jersey.spi.container.ContainerResponse.logException Mapped exception to response: 500 (Internal Server Error)
 org.apache.guacamole.rest.APIException
	at org.apache.guacamole.rest.RESTExceptionWrapper.invoke(RESTExceptionWrapper.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by aronson** [comment]
I just installed this extension myself into a guacamole docker instance earlier today, and I've encountered the same errors.
The extension loads fine, but once the website is accessed the exception prevents any and all access to guacamole through the guacamole web client.
I'm looking through building the source myself and I'm hoping the problem will be obvious.

**Comment by cicerofs** [comment]
If you find the solution put it here. I have tested in several environments and I still have the same problem.

**Comment by aronson** [comment]
I've found it!
Seems we both didn't realize there's some classpath assumptions when loading a jar :)
You need to include the libraries that the module uses on the classpath somehow. I believe it's possible to just drop the .jars into GUACAMOLE_HOME/lib, but what I did was create a "fatJar" with a new gradle task that added the external libraries into the final .jar.
Take a look here for the example I used, I just modified the build.gradle and added this task on a new line:
```Gradle
//create a single Jar with all dependencies
task fatJar(type: Jar) {
    manifest {
        attributes 'Implementation-Title': 'Guacamole Auth JWT',
                'Implementation-Version': version
    }
    baseName = project.name + '-all'
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}
```
Once I built the fatJar task with gradle, the new .jar it created worked flawlessly.
If you want to avoid the build, I assume you'll have to find the necessary .jar dependencies and copy them into the lib folder.

**Comment by cicerofs** [comment]
I added it to my gradle.build file but it did not work. How's your whole gradle.build?

**Comment by cicerofs** [comment]
I was able to use gradle build instead of gradle fatJar. Now it worked. Thank you.

**Comment by cicerofs** [comment]
Are you using the sample code in python? I could not even generate the url for connection. I get the response correctly.

**Comment by aronson** [comment]
I'm actually using .Net to create the JWT request and get back some JSON, here's my code with private information stripped, hopefully it helps you. I've provided the whole console app, although much of this can certainly be removed for your purposes.
The final result is a URL that you can launch to log into Guacamole in a normal session without additional authorization.
```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IdentityModel.Tokens.Jwt;
using System.Text;
using System.Net.Http;
using System.Security;
using Newtonsoft.Json;
using SecurityAlgorithms = Microsoft.IdentityModel.Tokens.SecurityAlgorithms;
using SigningCredentials = Microsoft.IdentityModel.Tokens.SigningCredentials;

namespace JwtPoc
{
    internal static class Program
    {
        /// <summary>
        /// A randomly-generated string with between 249 and 660 bits of entropy (blind) for HS256 authentication
        /// </summary>
        /// <remarks>
        /// <para>The string is in a human readable format for easy configuration with Guacamole, as it has poor string support.
        /// See https://xkpasswd.net/s/ for the generator. For security the parameters are not specified here.</para>
        /// </remarks>
        private const string SecureKeyString =
            "example-secure-secret-key";

        /// <summary>
        /// Microsoft recommends a single static HttpClient remain open for a given class
        /// </summary>
        private static readonly HttpClient WebClient = new HttpClient();

        /// <summary>
        /// Creates an authorization request for an RDP connection to EXAMPLE1 with hardcoded credentials.
        /// Sends this request to the remote Guacamole server and receives a one-time login token.
        /// </summary>
        private static void Main()
        {
            // Set up cryptographic parameters for the token
            var signingCredentials = GenerateSigningCredentials();
            var header = new JwtHeader(signingCredentials);

            // Create a unique connection ID -- needs improvement, maybe GUIDs?
            var connectionID = new Random().Next().ToString();

            // Create authorization information for a new Guacamole connection
            var payload = BuildJwtPayload(connectionID);

            // This string is the result of joining the crypto header and authorization claims payload into a JWT request
            var tokenAuthString = new JwtSecurityTokenHandler().WriteToken(new JwtSecurityToken(header, payload));

            // Send authorization request to Guacamole and retrieve response
            var tokenResponseJson = GetResponseString(tokenAuthString);

            // Adapt response into a pass/fail result that might be the valid login URL
            var result = ParseJwtResponse(tokenResponseJson, connectionID);
        }

        /// <summary>
        /// Creates a key-value pair of claims to authorize for a Guacamole connection and encodes it into a secure JWT payload
        /// </summary>
        /// <param name="randomId">The connection ID to use for this session</param>
        /// <returns>A JWT authorization for testUser on EXAMPLE1</returns>
        private static JwtPayload BuildJwtPayload(string randomId)
        {
            var payload = new JwtPayload
            {
                {"iat", DateTimeOffset.UtcNow.ToUnixTimeSeconds()},
                {"exp", DateTimeOffset.UtcNow.AddHours(2).ToUnixTimeSeconds()},
                {"GUAC_ID", randomId},
                {"guac.hostname", "EXAMPLE1.home"},
                {"guac.protocol", "rdp"},
                {"guac.port", 3389},
                {"guac.username", "testUser"},
                {"guac.password", "somePassword"},
                {"guac.domain", "EXDOMAIN"},
                {"guac.security", "nla"},
                {"guac.ignore-cert", "true"}
            };
            return payload;
        }

        /// <summary>
        /// Securely attempts authorization with the Guacamole JWT API and returns the result as JSON
        /// </summary>
        /// <param name="tokenString">A JWT request payload, encoded into a string</param>
        /// <returns>The text response from the Guacamole JWT HTTP API as the JSON content of the response</returns>
        private static string GetResponseString(string tokenString)
        {
            var values = new Dictionary<string, string> { { "token", tokenString } };
            var content = new FormUrlEncodedContent(values);
            var response = WebClient.PostAsync("http://192.168.1.7:8080/guacamole/api/tokens", content).Result;
            var responseString = response.Content.ReadAsStringAsync().Result;
            return responseString;
        }

        /// <summary>
        /// Encodes a private HMAC header to authenticate the JWT request to Guacamole
        /// </summary>
        /// <returns>An object that represents the shared secret transaction between this code and Guacamole</returns>
        private static SigningCredentials GenerateSigningCredentials()
        {
            var secureKeyAsBytes = Encoding.UTF8.GetBytes(SecureKeyString);
            var signingKey = new Microsoft.IdentityModel.Tokens.SymmetricSecurityKey(secureKeyAsBytes);
            var signingCredentials = new SigningCredentials(signingKey,
                SecurityAlgorithms.HmacSha256);
            return signingCredentials;
        }

        private static Result<string> ParseJwtResponse(string responseString, string connectionID)
        {
            // The leading component of a Guacamole login link
            const string authBaseUrl = "http://192.168.1.7:8080/guacamole/#/client";
            // Type is needed for the auth service
            const string guacamoleType = "GUAC_TYPE=c";
            // Data source informs auth service to use JWT login
            const string guacamoleDataSource = "GUAC_DATA_SOURCE=jwt";

            // JSON parsing to dynamic object
            dynamic response = JsonConvert.DeserializeObject(responseString);

            // If the response contains a fail result, could not authorize with JWT
            if (response.type == "INVALID_CREDENTIALS" || response.token == null)
                return Result<string>.CreateFail("Failed to authorize session with Guacamole backend server");

            // Token can be parsed from dynamic object at this point and is assumed to be valid
            var token = response.authToken;
            // Construct final URL with query string to login and return it
            return Result<string>.CreateSuccess(
                $"{authBaseUrl}?GUAC_ID={connectionID}&token={token}&{guacamoleType}&{guacamoleDataSource}");
        }
    }
    internal class Result<T>
    {
        internal enum ResultType { Success, Fail }
        internal ResultType Status { get; }
        internal Exception InnerException { get; }
        internal T ReturnValue { get; }
        internal Result(T returnValue, ResultType status, Exception innerException = null)
        {
            Status = status;
            ReturnValue = returnValue;
            InnerException = innerException;
        }

        internal static Result<T> CreateSuccess(T returnValue)
        {
            return new Result<T>(returnValue, ResultType.Success);
        }
        internal static Result<T> CreateFail(Exception innerException = null)
        {
            return new Result<T>(default(T), ResultType.Fail, innerException);
        }
        internal static Result<T> CreateFail(string failMessage)
        {
            return new Result<T>(default(T), ResultType.Fail, new Exception(failMessage));
        }
    }
}
```

**Comment by aiden0z** [comment]
@cicerofs  

You should check if  jwt jar located in GUACAMOLE_HOME/lib directory. Related document https://guacamole.incubator.apache.org/doc/gug/configuring-guacamole.html

```
GUACAMOLE_HOME

Guacamole reads files from its own configuration directory by default, resorting to the classpath only when this directory cannot be found. When locating this directory, Guacamole will try, in order:

The directory specified within the system property guacamole.home.

The directory specified within the environment variable GUACAMOLE_HOME.

The directory .guacamole, located within the home directory of the user running the servlet container.

This directory will be referred to as GUACAMOLE_HOME elsewhere in the documentation.

Guacamole uses GUACAMOLE_HOME as the primary search location for configuration file like guacamole.properties. The structure of GUACAMOLE_HOME is rigorously defined, and consists of the following optional files:


lib/
The search directory for libraries required by any Guacamole extensions. Guacamole will make the .jar files within this directory available to all extensions. If your extensions require additional libraries, such as database drivers, this is the proper place to put them.
```

For example if you use jetty to run guacamole, you should set `guacamole.home` system property to correct value. Bellow command set `guacamole.home` to  /etc/guacamole directory.

```
jetty -s /bin/bash -c /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Dguacamole.home=/etc/guacamole -Xmx512m -Djetty.home=/opt/jetty -Djetty.base=/opt/jetty -Djava.io.tmpdir=/tmp -jar /opt/jetty/start.jar jetty.port=8080 jetty.state=/opt/jetty/jetty.state jetty-started.xml
```

The tree of /etc/guacamole as follow:

```
 $ tree                                                                                                                                                                                         [9:09:19]
.
├── extensions
│   └── guacamole-auth-jwt-1.0.0.jar
├── guacamole.properties
├── lib
│   ├── jackson-annotations-2.8.0.jar
│   ├── jackson-core-2.8.2.jar
│   ├── jackson-databind-2.8.2.jar
│   └── jjwt-0.7.0.jar
└── logback.xml
```

**Comment by cicerofs** [comment]
Okay, now it's running 100%.

Taking advantage of the contact, is it possible to open more than one session in the same browser? Yeah, whenever I try to do that the previous session is closed. I think this is because the home session is spawned a new user. User "412a1d10-4461-4f01-b7a5-d3b8ded77dfc" successfully authenticated from .....

**Comment by aiden0z** [comment]
@cicerofs 

It seems you are used  RDP protocol. RDP protocol cant not share by default. If you want share RDP session, you should use guacamole database authentication plugin which support share RDP or VNC protocol.

refer:
- https://guacamole.incubator.apache.org/doc/gug/jdbc-auth.html#jdbc-auth-schema-sharing-profiles
- https://guacamole.incubator.apache.org/doc/gug/using-guacamole.html#client-share-menu
